### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by watchmexiang** [fyangneil/pavement-crack-detection#1]
Hello, I want to download your data set, but your data set is shared in Google Drive. I can't download it. Is there any other way to get the data set you share, such as Baidu Yunpan? Thank you.

**Comment by fyangneil** [comment]
Thanks for your interests in our work..
i will upload it to  Baidu Yunpan ASAP.

Fan

**Comment by fyangneil** [comment]
The datasets and model have beed uploaded to Baidu Yunpan, please check it out.
