### ISSUE TITLE
solver_fuse_fpn.prototxt

### ISSUE THREAD

**Issue by ling20180713** [fyangneil/pavement-crack-detection#2]
where is  the solver_fuse_fpn.prototxt?

**Comment by fyangneil** [comment]
sorry 
the file name should be train_fpn_crack.prototxt or train_fphb_crack.prototxt

**Comment by ling20180713** [comment]
Excuse me, I want to test the model  you shared, but I can't run it when I run it with HED_tutorial. It is normal to test the HED model.How should I test?
![q](https://user-images.githubusercontent.com/41189455/54807373-fda9ca80-4cb7-11e9-8c11-0a6d7ac1523a.png)

**Comment by fyangneil** [comment]
could you show me more information about the errors.

Fan

**Comment by ling20180713** [comment]
terminal show:
![t](https://user-images.githubusercontent.com/41189455/54813232-0efad300-4cc8-11e9-954d-ec000e2f16b2.png)

**Comment by fyangneil** [comment]
are you using the  test_fphb_crack.prototxt file?

**Comment by ling20180713** [comment]
yes,i use the test_fphb_crack.prototxt and fphb_crack.caffemodel

**Comment by fyangneil** [comment]
i modified the 'test_fphb_crack.prototxt' file, this time it should work. Please check it out

**Comment by fyangneil** [comment]
> yes,i use the test_fphb_crack.prototxt and fphb_crack.caffemodel
