### ISSUE TITLE
Testing result issue

### ISSUE THREAD

**Issue by candy0530** [fyangneil/pavement-crack-detection#7]
I tried the project you provided, but I got some errors.
I used model **trainedmodel/fphb_crack.caffemodel** which downloaded from Google Drive, dataset **CRACK500 test.txt** also downloaded from Google Drive and **test.py** with **test_fphb_crack.prototxt**, but I got error messages. 
```F0613 18:57:03.865557 146139 net.cpp:861] Cannot copy param 0 weights from layer 'conv4_fuse'; shape mismatch.  Source param shape is 512 1024 1 1 (524288); target param shape is 512 2048 3 3 (9437184). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.```

I replaced layers name `conv1_fuse, conv2_fuse, conv3_fuse, conv4_fuse, conv5_fuse, score-dsn1, score-dsn2, score-dsn3, score-dsn4, score-dsn5` to `conv1_fuse_1, conv2_fuse_1, conv3_fuse_1, conv4_fuse_1, conv5_fuse_1, score-dsn1_1, score-dsn2_1, score-dsn3_1, score-dsn4_1, score-dsn5_1`. It works, but I got all black result images.

Did I do wrong steps or miss some steps? How can I get normal results? Thanks!

**Comment by fyangneil** [comment]
@candy0530 
i will double check the model and prototxt file this weekend

**Comment by fyangneil** [comment]
@candy0530 
i have tested it and it works. Have you tried  the FPHB-tutorial in example folder? please try it first, let me know if it does not work.

**Comment by candy0530** [comment]
@fyangneil 
I re-downloaded model **trainedmodel/fphb_crack.caffemodel** again, finally it works with **test.py** and with **test_fphb_crack.prototxt**. But I got another issue.

I trained a model by **solve_fphb_crack.py** with **train_fphb_crack.prototxt** and get a model named **fphb_iiter_20000.caffemodel**. When I used this model with **test_fphb_crack.prototxt**, I got the same error messages. Aren't **test_fphb_crack.prototxt** and **train_fphb_crack.prototxt** same structures? How can I alter **train_fphb_crack.prototxt** to a correct **test_fphb_crack.prototxt**?

Thanks a lot!

**Comment by fyangneil** [comment]
yes，the training and test files are a little different, I will modify it
tomorrow.

**Comment by fyangneil** [comment]
@candy0530 you could try the test_fphb_crack_v1 file. if it does not work, let me know

**Comment by candy0530** [comment]
@fyangneil 
It does not work.
But I found typo in **solver_fphb_crack.prototxt**.
```
net: "train_fpn_crack.prototxt"
```
Due to this line, I used FPN model structure to train the FPHB model, so it works with **test_fpn_crack.prototxt**.
So it should be "net: train_**fphb**_crack.prototxt" at first line in **solver_fphb_crack.prototxt**.
Do I misunderstand the code?

**Comment by fyangneil** [comment]
yes，you are right. does it work？

**Comment by candy0530** [comment]
It works! Thanks a lot!
